development:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "http://example.com/faye"
  secret_token: "f4e840561ddba9ff8ff0d6f8e847a6aac57a7fa272f940e07e868aceae4b0127"
  signature_expiration: 3600 # one hour
